namespace Stripe.SetupAttempt

open System.Text.Json.Serialization
open FunStripe
open System
open Stripe.PaymentMethod

[<System.CodeDom.Compiler.GeneratedCode("FunStripe", "2.0.4")>]
type SetupAttemptCustomer'AnyOf =
    | String of string
    | Customer of Customer
    | DeletedCustomer of DeletedCustomer

[<Struct>]
type SetupAttemptFlowDirections =
    | Inbound
    | Outbound

type SetupAttemptPaymentMethodDetailsAcssDebit =
    { SetupAttemptPaymentMethodDetailsAcssDebit: string option }

type SetupAttemptPaymentMethodDetailsAcssDebit with
    static member New(?setupAttemptPaymentMethodDetailsAcssDebit: string option) =
        {
            SetupAttemptPaymentMethodDetailsAcssDebit = setupAttemptPaymentMethodDetailsAcssDebit |> Option.flatten
        }

type SetupAttemptPaymentMethodDetailsAmazonPay =
    { SetupAttemptPaymentMethodDetailsAmazonPay: string option }

type SetupAttemptPaymentMethodDetailsAmazonPay with
    static member New(?setupAttemptPaymentMethodDetailsAmazonPay: string option) =
        {
            SetupAttemptPaymentMethodDetailsAmazonPay = setupAttemptPaymentMethodDetailsAmazonPay |> Option.flatten
        }

type SetupAttemptPaymentMethodDetailsAuBecsDebit =
    { SetupAttemptPaymentMethodDetailsAuBecsDebit: string option }

type SetupAttemptPaymentMethodDetailsAuBecsDebit with
    static member New(?setupAttemptPaymentMethodDetailsAuBecsDebit: string option) =
        {
            SetupAttemptPaymentMethodDetailsAuBecsDebit = setupAttemptPaymentMethodDetailsAuBecsDebit |> Option.flatten
        }

type SetupAttemptPaymentMethodDetailsBacsDebit =
    { SetupAttemptPaymentMethodDetailsBacsDebit: string option }

type SetupAttemptPaymentMethodDetailsBacsDebit with
    static member New(?setupAttemptPaymentMethodDetailsBacsDebit: string option) =
        {
            SetupAttemptPaymentMethodDetailsBacsDebit = setupAttemptPaymentMethodDetailsBacsDebit |> Option.flatten
        }

[<Struct>]
type SetupAttemptPaymentMethodDetailsBancontactPreferredLanguage =
    | De
    | En
    | Fr
    | Nl

type SetupAttemptPaymentMethodDetailsBancontact =
    {
        /// Bank code of bank associated with the bank account.
        BankCode: string option
        /// Name of the bank associated with the bank account.
        BankName: string option
        /// Bank Identifier Code of the bank associated with the bank account.
        Bic: string option
        /// The ID of the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
        GeneratedSepaDebit: StripeId<Markers.PaymentMethod> option
        /// The mandate for the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
        GeneratedSepaDebitMandate: StripeId<Markers.Mandate> option
        /// Last four characters of the IBAN.
        [<JsonPropertyName("iban_last4")>]
        IbanLast4: string option
        /// Preferred language of the Bancontact authorization page that the customer is redirected to.
        /// Can be one of `en`, `de`, `fr`, or `nl`
        PreferredLanguage: SetupAttemptPaymentMethodDetailsBancontactPreferredLanguage option
        /// Owner's verified full name. Values are verified or provided by Bancontact directly
        /// (if supported) at the time of authorization or settlement. They cannot be set or mutated.
        VerifiedName: string option
    }

type SetupAttemptPaymentMethodDetailsBancontact with
    static member New(bankCode: string option, bankName: string option, bic: string option, generatedSepaDebit: StripeId<Markers.PaymentMethod> option, generatedSepaDebitMandate: StripeId<Markers.Mandate> option, ibanLast4: string option, preferredLanguage: SetupAttemptPaymentMethodDetailsBancontactPreferredLanguage option, verifiedName: string option) =
        {
            BankCode = bankCode
            BankName = bankName
            Bic = bic
            GeneratedSepaDebit = generatedSepaDebit
            GeneratedSepaDebitMandate = generatedSepaDebitMandate
            IbanLast4 = ibanLast4
            PreferredLanguage = preferredLanguage
            VerifiedName = verifiedName
        }

type SetupAttemptPaymentMethodDetailsBoleto =
    { SetupAttemptPaymentMethodDetailsBoleto: string option }

type SetupAttemptPaymentMethodDetailsBoleto with
    static member New(?setupAttemptPaymentMethodDetailsBoleto: string option) =
        {
            SetupAttemptPaymentMethodDetailsBoleto = setupAttemptPaymentMethodDetailsBoleto |> Option.flatten
        }

type SetupAttemptPaymentMethodDetailsCardBrand =
    | Amex
    | CartesBancaires
    | Diners
    | Discover
    | EftposAu
    | Jcb
    | Link
    | Mastercard
    | Unionpay
    | Visa
    | Unknown

[<Struct>]
type SetupAttemptPaymentMethodDetailsCardChecksAddressLine1Check =
    | Pass
    | Fail
    | Unavailable
    | Unchecked

[<Struct>]
type SetupAttemptPaymentMethodDetailsCardChecksAddressPostalCodeCheck =
    | Pass
    | Fail
    | Unavailable
    | Unchecked

[<Struct>]
type SetupAttemptPaymentMethodDetailsCardChecksCvcCheck =
    | Pass
    | Fail
    | Unavailable
    | Unchecked

type SetupAttemptPaymentMethodDetailsCardChecks =
    {
        /// If a address line1 was provided, results of the check, one of `pass`, `fail`, `unavailable`, or `unchecked`.
        [<JsonPropertyName("address_line1_check")>]
        AddressLine1Check: SetupAttemptPaymentMethodDetailsCardChecksAddressLine1Check option
        /// If a address postal code was provided, results of the check, one of `pass`, `fail`, `unavailable`, or `unchecked`.
        AddressPostalCodeCheck: SetupAttemptPaymentMethodDetailsCardChecksAddressPostalCodeCheck option
        /// If a CVC was provided, results of the check, one of `pass`, `fail`, `unavailable`, or `unchecked`.
        CvcCheck: SetupAttemptPaymentMethodDetailsCardChecksCvcCheck option
    }

type SetupAttemptPaymentMethodDetailsCardChecks with
    static member New(addressLine1Check: SetupAttemptPaymentMethodDetailsCardChecksAddressLine1Check option, addressPostalCodeCheck: SetupAttemptPaymentMethodDetailsCardChecksAddressPostalCodeCheck option, cvcCheck: SetupAttemptPaymentMethodDetailsCardChecksCvcCheck option) =
        {
            AddressLine1Check = addressLine1Check
            AddressPostalCodeCheck = addressPostalCodeCheck
            CvcCheck = cvcCheck
        }

[<Struct>]
type SetupAttemptPaymentMethodDetailsCardFunding =
    | Credit
    | Debit
    | Prepaid
    | Unknown

type SetupAttemptPaymentMethodDetailsCardNetwork =
    | Amex
    | CartesBancaires
    | Diners
    | Discover
    | EftposAu
    | Interac
    | Jcb
    | Link
    | Mastercard
    | Unionpay
    | Visa
    | Unknown

[<Struct>]
type SetupAttemptPaymentMethodDetailsCardWalletType =
    | ApplePay
    | GooglePay
    | Link

type SetupAttemptPaymentMethodDetailsCardWallet =
    {
        ApplePay: PaymentMethodDetailsCardWalletApplePay option
        GooglePay: PaymentMethodDetailsCardWalletGooglePay option
        /// The type of the card wallet, one of `apple_pay`, `google_pay`, or `link`. An additional hash is included on the Wallet subhash with a name matching this value. It contains additional information specific to the card wallet type.
        Type: SetupAttemptPaymentMethodDetailsCardWalletType
    }

type SetupAttemptPaymentMethodDetailsCardWallet with
    static member New(``type``: SetupAttemptPaymentMethodDetailsCardWalletType, ?applePay: PaymentMethodDetailsCardWalletApplePay, ?googlePay: PaymentMethodDetailsCardWalletGooglePay) =
        {
            Type = ``type``
            ApplePay = applePay
            GooglePay = googlePay
        }

[<Struct>]
type ThreeDSecureDetailsAuthenticationFlow =
    | Challenge
    | Frictionless

[<Struct>]
type ThreeDSecureDetailsElectronicCommerceIndicator =
    | [<JsonPropertyName("01")>] Numeric01
    | [<JsonPropertyName("02")>] Numeric02
    | [<JsonPropertyName("05")>] Numeric05
    | [<JsonPropertyName("06")>] Numeric06
    | [<JsonPropertyName("07")>] Numeric07

type ThreeDSecureDetailsResult =
    | AttemptAcknowledged
    | Authenticated
    | Exempted
    | Failed
    | NotSupported
    | ProcessingError

type ThreeDSecureDetailsResultReason =
    | Abandoned
    | Bypassed
    | Canceled
    | CardNotEnrolled
    | NetworkNotSupported
    | ProtocolError
    | Rejected

[<Struct>]
type ThreeDSecureDetailsVersion =
    | [<JsonPropertyName("1.0.2")>] Numeric102
    | [<JsonPropertyName("2.1.0")>] Numeric210
    | [<JsonPropertyName("2.2.0")>] Numeric220
    | [<JsonPropertyName("2.3.0")>] Numeric230
    | [<JsonPropertyName("2.3.1")>] Numeric231

type ThreeDSecureDetails =
    {
        /// For authenticated transactions: how the customer was authenticated by
        /// the issuing bank.
        AuthenticationFlow: ThreeDSecureDetailsAuthenticationFlow option
        /// The Electronic Commerce Indicator (ECI). A protocol-level field
        /// indicating what degree of authentication was performed.
        ElectronicCommerceIndicator: ThreeDSecureDetailsElectronicCommerceIndicator option
        /// Indicates the outcome of 3D Secure authentication.
        Result: ThreeDSecureDetailsResult option
        /// Additional information about why 3D Secure succeeded or failed based
        /// on the `result`.
        ResultReason: ThreeDSecureDetailsResultReason option
        /// The 3D Secure 1 XID or 3D Secure 2 Directory Server Transaction ID
        /// (dsTransId) for this payment.
        TransactionId: string option
        /// The version of 3D Secure that was used.
        Version: ThreeDSecureDetailsVersion option
    }

type ThreeDSecureDetails with
    static member New(authenticationFlow: ThreeDSecureDetailsAuthenticationFlow option, electronicCommerceIndicator: ThreeDSecureDetailsElectronicCommerceIndicator option, result: ThreeDSecureDetailsResult option, resultReason: ThreeDSecureDetailsResultReason option, transactionId: string option, version: ThreeDSecureDetailsVersion option) =
        {
            AuthenticationFlow = authenticationFlow
            ElectronicCommerceIndicator = electronicCommerceIndicator
            Result = result
            ResultReason = resultReason
            TransactionId = transactionId
            Version = version
        }

type SetupAttemptPaymentMethodDetailsCard =
    {
        /// Card brand. Can be `amex`, `cartes_bancaires`, `diners`, `discover`, `eftpos_au`, `jcb`, `link`, `mastercard`, `unionpay`, `visa` or `unknown`.
        Brand: SetupAttemptPaymentMethodDetailsCardBrand option
        /// Check results by Card networks on Card address and CVC at the time of authorization
        Checks: SetupAttemptPaymentMethodDetailsCardChecks option
        /// Two-letter ISO code representing the country of the card. You could use this attribute to get a sense of the international breakdown of cards you've collected.
        Country: IsoTypes.IsoCountryCode option
        /// A high-level description of the type of cards issued in this range. (For internal use only and not typically available in standard API requests.)
        Description: string option
        /// Two-digit number representing the card's expiration month.
        ExpMonth: int option
        /// Four-digit number representing the card's expiration year.
        ExpYear: int option
        /// Uniquely identifies this particular card number. You can use this attribute to check whether two customers who’ve signed up with you are using the same card number, for example. For payment methods that tokenize card information (Apple Pay, Google Pay), the tokenized number might be provided instead of the underlying card number.
        /// *As of May 1, 2021, card fingerprint in India for Connect changed to allow two fingerprints for the same card---one for India and one for the rest of the world.*
        Fingerprint: string option
        /// Card funding type. Can be `credit`, `debit`, `prepaid`, or `unknown`.
        Funding: SetupAttemptPaymentMethodDetailsCardFunding option
        /// Issuer identification number of the card. (For internal use only and not typically available in standard API requests.)
        Iin: string option
        /// The name of the card's issuing bank. (For internal use only and not typically available in standard API requests.)
        Issuer: string option
        /// The last four digits of the card.
        [<JsonPropertyName("last4")>]
        Last4: string option
        /// True if this payment was marked as MOTO and out of scope for SCA.
        Moto: bool option
        /// Identifies which network this charge was processed on. Can be `amex`, `cartes_bancaires`, `diners`, `discover`, `eftpos_au`, `interac`, `jcb`, `link`, `mastercard`, `unionpay`, `visa`, or `unknown`.
        Network: SetupAttemptPaymentMethodDetailsCardNetwork option
        /// Populated if this authorization used 3D Secure authentication.
        ThreeDSecure: ThreeDSecureDetails option
        /// If this Card is part of a card wallet, this contains the details of the card wallet.
        Wallet: SetupAttemptPaymentMethodDetailsCardWallet option
    }

type SetupAttemptPaymentMethodDetailsCard with
    static member New(brand: SetupAttemptPaymentMethodDetailsCardBrand option, checks: SetupAttemptPaymentMethodDetailsCardChecks option, country: IsoTypes.IsoCountryCode option, expMonth: int option, expYear: int option, funding: SetupAttemptPaymentMethodDetailsCardFunding option, last4: string option, network: SetupAttemptPaymentMethodDetailsCardNetwork option, threeDSecure: ThreeDSecureDetails option, wallet: SetupAttemptPaymentMethodDetailsCardWallet option, ?description: string option, ?fingerprint: string option, ?iin: string option, ?issuer: string option, ?moto: bool) =
        {
            Brand = brand
            Checks = checks
            Country = country
            ExpMonth = expMonth
            ExpYear = expYear
            Funding = funding
            Last4 = last4
            Network = network
            ThreeDSecure = threeDSecure
            Wallet = wallet
            Description = description |> Option.flatten
            Fingerprint = fingerprint |> Option.flatten
            Iin = iin |> Option.flatten
            Issuer = issuer |> Option.flatten
            Moto = moto
        }

type SetupAttemptPaymentMethodDetailsCardPresent =
    {
        /// The ID of the Card PaymentMethod which was generated by this SetupAttempt.
        GeneratedCard: StripeId<Markers.PaymentMethod> option
        /// Details about payments collected offline.
        Offline: PaymentMethodDetailsCardPresentOffline option
    }

type SetupAttemptPaymentMethodDetailsCardPresent with
    static member New(generatedCard: StripeId<Markers.PaymentMethod> option, offline: PaymentMethodDetailsCardPresentOffline option) =
        {
            GeneratedCard = generatedCard
            Offline = offline
        }

type SetupAttemptPaymentMethodDetailsCashapp =
    { SetupAttemptPaymentMethodDetailsCashapp: string option }

type SetupAttemptPaymentMethodDetailsCashapp with
    static member New(?setupAttemptPaymentMethodDetailsCashapp: string option) =
        {
            SetupAttemptPaymentMethodDetailsCashapp = setupAttemptPaymentMethodDetailsCashapp |> Option.flatten
        }

type SetupAttemptPaymentMethodDetailsIdealBank =
    | AbnAmro
    | Adyen
    | AsnBank
    | Bunq
    | Buut
    | Finom
    | Handelsbanken
    | Ing
    | Knab
    | Mollie
    | Moneyou
    | N26
    | Nn
    | Rabobank
    | Regiobank
    | Revolut
    | SnsBank
    | TriodosBank
    | VanLanschot
    | Yoursafe

type SetupAttemptPaymentMethodDetailsIdealBic =
    | [<JsonPropertyName("ABNANL2A")>] ABNANL2A
    | [<JsonPropertyName("ADYBNL2A")>] ADYBNL2A
    | [<JsonPropertyName("ASNBNL21")>] ASNBNL21
    | [<JsonPropertyName("BITSNL2A")>] BITSNL2A
    | [<JsonPropertyName("BUNQNL2A")>] BUNQNL2A
    | [<JsonPropertyName("BUUTNL2A")>] BUUTNL2A
    | [<JsonPropertyName("FNOMNL22")>] FNOMNL22
    | [<JsonPropertyName("FVLBNL22")>] FVLBNL22
    | [<JsonPropertyName("HANDNL2A")>] HANDNL2A
    | [<JsonPropertyName("INGBNL2A")>] INGBNL2A
    | [<JsonPropertyName("KNABNL2H")>] KNABNL2H
    | [<JsonPropertyName("MLLENL2A")>] MLLENL2A
    | [<JsonPropertyName("MOYONL21")>] MOYONL21
    | [<JsonPropertyName("NNBANL2G")>] NNBANL2G
    | [<JsonPropertyName("NTSBDEB1")>] NTSBDEB1
    | [<JsonPropertyName("RABONL2U")>] RABONL2U
    | [<JsonPropertyName("RBRBNL21")>] RBRBNL21
    | [<JsonPropertyName("REVOIE23")>] REVOIE23
    | [<JsonPropertyName("REVOLT21")>] REVOLT21
    | [<JsonPropertyName("SNSBNL2A")>] SNSBNL2A
    | [<JsonPropertyName("TRIONL2U")>] TRIONL2U

type SetupAttemptPaymentMethodDetailsIdeal =
    {
        /// The customer's bank. Can be one of `abn_amro`, `adyen`, `asn_bank`, `bunq`, `buut`, `finom`, `handelsbanken`, `ing`, `knab`, `mollie`, `moneyou`, `n26`, `nn`, `rabobank`, `regiobank`, `revolut`, `sns_bank`, `triodos_bank`, `van_lanschot`, or `yoursafe`.
        Bank: SetupAttemptPaymentMethodDetailsIdealBank option
        /// The Bank Identifier Code of the customer's bank.
        Bic: SetupAttemptPaymentMethodDetailsIdealBic option
        /// The ID of the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
        GeneratedSepaDebit: StripeId<Markers.PaymentMethod> option
        /// The mandate for the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
        GeneratedSepaDebitMandate: StripeId<Markers.Mandate> option
        /// Last four characters of the IBAN.
        [<JsonPropertyName("iban_last4")>]
        IbanLast4: string option
        /// Owner's verified full name. Values are verified or provided by iDEAL directly
        /// (if supported) at the time of authorization or settlement. They cannot be set or mutated.
        VerifiedName: string option
    }

type SetupAttemptPaymentMethodDetailsIdeal with
    static member New(bank: SetupAttemptPaymentMethodDetailsIdealBank option, bic: SetupAttemptPaymentMethodDetailsIdealBic option, generatedSepaDebit: StripeId<Markers.PaymentMethod> option, generatedSepaDebitMandate: StripeId<Markers.Mandate> option, ibanLast4: string option, verifiedName: string option) =
        {
            Bank = bank
            Bic = bic
            GeneratedSepaDebit = generatedSepaDebit
            GeneratedSepaDebitMandate = generatedSepaDebitMandate
            IbanLast4 = ibanLast4
            VerifiedName = verifiedName
        }

type SetupAttemptPaymentMethodDetailsKakaoPay =
    { SetupAttemptPaymentMethodDetailsKakaoPay: string option }

type SetupAttemptPaymentMethodDetailsKakaoPay with
    static member New(?setupAttemptPaymentMethodDetailsKakaoPay: string option) =
        {
            SetupAttemptPaymentMethodDetailsKakaoPay = setupAttemptPaymentMethodDetailsKakaoPay |> Option.flatten
        }

type SetupAttemptPaymentMethodDetailsKlarna =
    { SetupAttemptPaymentMethodDetailsKlarna: string option }

type SetupAttemptPaymentMethodDetailsKlarna with
    static member New(?setupAttemptPaymentMethodDetailsKlarna: string option) =
        {
            SetupAttemptPaymentMethodDetailsKlarna = setupAttemptPaymentMethodDetailsKlarna |> Option.flatten
        }

type SetupAttemptPaymentMethodDetailsKrCard =
    { SetupAttemptPaymentMethodDetailsKrCard: string option }

type SetupAttemptPaymentMethodDetailsKrCard with
    static member New(?setupAttemptPaymentMethodDetailsKrCard: string option) =
        {
            SetupAttemptPaymentMethodDetailsKrCard = setupAttemptPaymentMethodDetailsKrCard |> Option.flatten
        }

type SetupAttemptPaymentMethodDetailsLink =
    { SetupAttemptPaymentMethodDetailsLink: string option }

type SetupAttemptPaymentMethodDetailsLink with
    static member New(?setupAttemptPaymentMethodDetailsLink: string option) =
        {
            SetupAttemptPaymentMethodDetailsLink = setupAttemptPaymentMethodDetailsLink |> Option.flatten
        }

type SetupAttemptPaymentMethodDetailsNaverPay =
    {
        /// Uniquely identifies this particular Naver Pay account. You can use this attribute to check whether two Naver Pay accounts are the same.
        BuyerId: string option
    }

type SetupAttemptPaymentMethodDetailsNaverPay with
    static member New(?buyerId: string) =
        {
            BuyerId = buyerId
        }

type SetupAttemptPaymentMethodDetailsNzBankAccount =
    { SetupAttemptPaymentMethodDetailsNzBankAccount: string option }

type SetupAttemptPaymentMethodDetailsNzBankAccount with
    static member New(?setupAttemptPaymentMethodDetailsNzBankAccount: string option) =
        {
            SetupAttemptPaymentMethodDetailsNzBankAccount = setupAttemptPaymentMethodDetailsNzBankAccount |> Option.flatten
        }

type SetupAttemptPaymentMethodDetailsPaypal =
    { SetupAttemptPaymentMethodDetailsPaypal: string option }

type SetupAttemptPaymentMethodDetailsPaypal with
    static member New(?setupAttemptPaymentMethodDetailsPaypal: string option) =
        {
            SetupAttemptPaymentMethodDetailsPaypal = setupAttemptPaymentMethodDetailsPaypal |> Option.flatten
        }

type SetupAttemptPaymentMethodDetailsPayto =
    { SetupAttemptPaymentMethodDetailsPayto: string option }

type SetupAttemptPaymentMethodDetailsPayto with
    static member New(?setupAttemptPaymentMethodDetailsPayto: string option) =
        {
            SetupAttemptPaymentMethodDetailsPayto = setupAttemptPaymentMethodDetailsPayto |> Option.flatten
        }

type SetupAttemptPaymentMethodDetailsPix =
    { SetupAttemptPaymentMethodDetailsPix: string option }

type SetupAttemptPaymentMethodDetailsPix with
    static member New(?setupAttemptPaymentMethodDetailsPix: string option) =
        {
            SetupAttemptPaymentMethodDetailsPix = setupAttemptPaymentMethodDetailsPix |> Option.flatten
        }

type SetupAttemptPaymentMethodDetailsRevolutPay =
    { SetupAttemptPaymentMethodDetailsRevolutPay: string option }

type SetupAttemptPaymentMethodDetailsRevolutPay with
    static member New(?setupAttemptPaymentMethodDetailsRevolutPay: string option) =
        {
            SetupAttemptPaymentMethodDetailsRevolutPay = setupAttemptPaymentMethodDetailsRevolutPay |> Option.flatten
        }

type SetupAttemptPaymentMethodDetailsSepaDebit =
    { SetupAttemptPaymentMethodDetailsSepaDebit: string option }

type SetupAttemptPaymentMethodDetailsSepaDebit with
    static member New(?setupAttemptPaymentMethodDetailsSepaDebit: string option) =
        {
            SetupAttemptPaymentMethodDetailsSepaDebit = setupAttemptPaymentMethodDetailsSepaDebit |> Option.flatten
        }

[<Struct>]
type SetupAttemptPaymentMethodDetailsSofortPreferredLanguage =
    | De
    | En
    | Fr
    | Nl

type SetupAttemptPaymentMethodDetailsSofort =
    {
        /// Bank code of bank associated with the bank account.
        BankCode: string option
        /// Name of the bank associated with the bank account.
        BankName: string option
        /// Bank Identifier Code of the bank associated with the bank account.
        Bic: string option
        /// The ID of the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
        GeneratedSepaDebit: StripeId<Markers.PaymentMethod> option
        /// The mandate for the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
        GeneratedSepaDebitMandate: StripeId<Markers.Mandate> option
        /// Last four characters of the IBAN.
        [<JsonPropertyName("iban_last4")>]
        IbanLast4: string option
        /// Preferred language of the Sofort authorization page that the customer is redirected to.
        /// Can be one of `en`, `de`, `fr`, or `nl`
        PreferredLanguage: SetupAttemptPaymentMethodDetailsSofortPreferredLanguage option
        /// Owner's verified full name. Values are verified or provided by Sofort directly
        /// (if supported) at the time of authorization or settlement. They cannot be set or mutated.
        VerifiedName: string option
    }

type SetupAttemptPaymentMethodDetailsSofort with
    static member New(bankCode: string option, bankName: string option, bic: string option, generatedSepaDebit: StripeId<Markers.PaymentMethod> option, generatedSepaDebitMandate: StripeId<Markers.Mandate> option, ibanLast4: string option, preferredLanguage: SetupAttemptPaymentMethodDetailsSofortPreferredLanguage option, verifiedName: string option) =
        {
            BankCode = bankCode
            BankName = bankName
            Bic = bic
            GeneratedSepaDebit = generatedSepaDebit
            GeneratedSepaDebitMandate = generatedSepaDebitMandate
            IbanLast4 = ibanLast4
            PreferredLanguage = preferredLanguage
            VerifiedName = verifiedName
        }

type SetupAttemptPaymentMethodDetailsUpi =
    { SetupAttemptPaymentMethodDetailsUpi: string option }

type SetupAttemptPaymentMethodDetailsUpi with
    static member New(?setupAttemptPaymentMethodDetailsUpi: string option) =
        {
            SetupAttemptPaymentMethodDetailsUpi = setupAttemptPaymentMethodDetailsUpi |> Option.flatten
        }

type SetupAttemptPaymentMethodDetailsUsBankAccount =
    { SetupAttemptPaymentMethodDetailsUsBankAccount: string option }

type SetupAttemptPaymentMethodDetailsUsBankAccount with
    static member New(?setupAttemptPaymentMethodDetailsUsBankAccount: string option) =
        {
            SetupAttemptPaymentMethodDetailsUsBankAccount = setupAttemptPaymentMethodDetailsUsBankAccount |> Option.flatten
        }

type SetupAttemptPaymentMethodDetails =
    {
        AcssDebit: SetupAttemptPaymentMethodDetailsAcssDebit option
        AmazonPay: SetupAttemptPaymentMethodDetailsAmazonPay option
        AuBecsDebit: SetupAttemptPaymentMethodDetailsAuBecsDebit option
        BacsDebit: SetupAttemptPaymentMethodDetailsBacsDebit option
        Bancontact: SetupAttemptPaymentMethodDetailsBancontact option
        Boleto: SetupAttemptPaymentMethodDetailsBoleto option
        Card: SetupAttemptPaymentMethodDetailsCard option
        CardPresent: SetupAttemptPaymentMethodDetailsCardPresent option
        Cashapp: SetupAttemptPaymentMethodDetailsCashapp option
        Ideal: SetupAttemptPaymentMethodDetailsIdeal option
        KakaoPay: SetupAttemptPaymentMethodDetailsKakaoPay option
        Klarna: SetupAttemptPaymentMethodDetailsKlarna option
        KrCard: SetupAttemptPaymentMethodDetailsKrCard option
        Link: SetupAttemptPaymentMethodDetailsLink option
        NaverPay: SetupAttemptPaymentMethodDetailsNaverPay option
        NzBankAccount: SetupAttemptPaymentMethodDetailsNzBankAccount option
        Paypal: SetupAttemptPaymentMethodDetailsPaypal option
        Payto: SetupAttemptPaymentMethodDetailsPayto option
        Pix: SetupAttemptPaymentMethodDetailsPix option
        RevolutPay: SetupAttemptPaymentMethodDetailsRevolutPay option
        SepaDebit: SetupAttemptPaymentMethodDetailsSepaDebit option
        Sofort: SetupAttemptPaymentMethodDetailsSofort option
        /// The type of the payment method used in the SetupIntent (e.g., `card`). An additional hash is included on `payment_method_details` with a name matching this value. It contains confirmation-specific information for the payment method.
        Type: string
        Upi: SetupAttemptPaymentMethodDetailsUpi option
        UsBankAccount: SetupAttemptPaymentMethodDetailsUsBankAccount option
    }

type SetupAttemptPaymentMethodDetails with
    static member New(``type``: string, ?acssDebit: SetupAttemptPaymentMethodDetailsAcssDebit, ?amazonPay: SetupAttemptPaymentMethodDetailsAmazonPay, ?auBecsDebit: SetupAttemptPaymentMethodDetailsAuBecsDebit, ?bacsDebit: SetupAttemptPaymentMethodDetailsBacsDebit, ?bancontact: SetupAttemptPaymentMethodDetailsBancontact, ?boleto: SetupAttemptPaymentMethodDetailsBoleto, ?card: SetupAttemptPaymentMethodDetailsCard, ?cardPresent: SetupAttemptPaymentMethodDetailsCardPresent, ?cashapp: SetupAttemptPaymentMethodDetailsCashapp, ?ideal: SetupAttemptPaymentMethodDetailsIdeal, ?kakaoPay: SetupAttemptPaymentMethodDetailsKakaoPay, ?klarna: SetupAttemptPaymentMethodDetailsKlarna, ?krCard: SetupAttemptPaymentMethodDetailsKrCard, ?link: SetupAttemptPaymentMethodDetailsLink, ?naverPay: SetupAttemptPaymentMethodDetailsNaverPay, ?nzBankAccount: SetupAttemptPaymentMethodDetailsNzBankAccount, ?paypal: SetupAttemptPaymentMethodDetailsPaypal, ?payto: SetupAttemptPaymentMethodDetailsPayto, ?pix: SetupAttemptPaymentMethodDetailsPix, ?revolutPay: SetupAttemptPaymentMethodDetailsRevolutPay, ?sepaDebit: SetupAttemptPaymentMethodDetailsSepaDebit, ?sofort: SetupAttemptPaymentMethodDetailsSofort, ?upi: SetupAttemptPaymentMethodDetailsUpi, ?usBankAccount: SetupAttemptPaymentMethodDetailsUsBankAccount) =
        {
            Type = ``type``
            AcssDebit = acssDebit
            AmazonPay = amazonPay
            AuBecsDebit = auBecsDebit
            BacsDebit = bacsDebit
            Bancontact = bancontact
            Boleto = boleto
            Card = card
            CardPresent = cardPresent
            Cashapp = cashapp
            Ideal = ideal
            KakaoPay = kakaoPay
            Klarna = klarna
            KrCard = krCard
            Link = link
            NaverPay = naverPay
            NzBankAccount = nzBankAccount
            Paypal = paypal
            Payto = payto
            Pix = pix
            RevolutPay = revolutPay
            SepaDebit = sepaDebit
            Sofort = sofort
            Upi = upi
            UsBankAccount = usBankAccount
        }

type SetupAttemptStatus =
    | RequiresConfirmation
    | RequiresAction
    | Processing
    | Succeeded
    | Failed
    | Abandoned

[<Struct>]
type SetupAttemptUsage =
    | OffSession
    | OnSession

/// A SetupAttempt describes one attempted confirmation of a SetupIntent,
/// whether that confirmation is successful or unsuccessful. You can use
/// SetupAttempts to inspect details of a specific attempt at setting up a
/// payment method using a SetupIntent.
type SetupAttempt =
    {
        /// The value of [application](https://docs.stripe.com/api/setup_intents/object#setup_intent_object-application) on the SetupIntent at the time of this confirmation.
        Application: StripeId<Markers.Application> option
        /// If present, the SetupIntent's payment method will be attached to the in-context Stripe Account.
        /// It can only be used for this Stripe Account’s own money movement flows like InboundTransfer and OutboundTransfers. It cannot be set to true when setting up a PaymentMethod for a Customer, and defaults to false when attaching a PaymentMethod to a Customer.
        AttachToSelf: bool option
        /// Time at which the object was created. Measured in seconds since the Unix epoch.
        Created: DateTime
        /// The value of [customer](https://docs.stripe.com/api/setup_intents/object#setup_intent_object-customer) on the SetupIntent at the time of this confirmation.
        Customer: SetupAttemptCustomer'AnyOf option
        /// The value of [customer_account](https://docs.stripe.com/api/setup_intents/object#setup_intent_object-customer_account) on the SetupIntent at the time of this confirmation.
        CustomerAccount: string option
        /// Indicates the directions of money movement for which this payment method is intended to be used.
        /// Include `inbound` if you intend to use the payment method as the origin to pull funds from. Include `outbound` if you intend to use the payment method as the destination to send funds to. You can include both if you intend to use the payment method for both purposes.
        FlowDirections: SetupAttemptFlowDirections list option
        /// Unique identifier for the object.
        Id: string
        /// If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
        Livemode: bool
        /// The value of [on_behalf_of](https://docs.stripe.com/api/setup_intents/object#setup_intent_object-on_behalf_of) on the SetupIntent at the time of this confirmation.
        OnBehalfOf: StripeId<Markers.Account> option
        /// ID of the payment method used with this SetupAttempt.
        PaymentMethod: StripeId<Markers.PaymentMethod>
        PaymentMethodDetails: SetupAttemptPaymentMethodDetails
        /// The error encountered during this attempt to confirm the SetupIntent, if any.
        SetupError: ApiErrors option
        /// ID of the SetupIntent that this attempt belongs to.
        SetupIntent: StripeId<Markers.SetupIntent>
        /// Status of this SetupAttempt, one of `requires_confirmation`, `requires_action`, `processing`, `succeeded`, `failed`, or `abandoned`.
        Status: SetupAttemptStatus
        /// The value of [usage](https://docs.stripe.com/api/setup_intents/object#setup_intent_object-usage) on the SetupIntent at the time of this confirmation, one of `off_session` or `on_session`.
        Usage: SetupAttemptUsage
    }

type SetupAttempt with
    static member New(application: StripeId<Markers.Application> option, created: DateTime, customer: SetupAttemptCustomer'AnyOf option, customerAccount: string option, flowDirections: SetupAttemptFlowDirections list option, id: string, livemode: bool, onBehalfOf: StripeId<Markers.Account> option, paymentMethod: StripeId<Markers.PaymentMethod>, paymentMethodDetails: SetupAttemptPaymentMethodDetails, setupError: ApiErrors option, setupIntent: StripeId<Markers.SetupIntent>, status: SetupAttemptStatus, usage: SetupAttemptUsage, ?attachToSelf: bool) =
        {
            Application = application
            Created = created
            Customer = customer
            CustomerAccount = customerAccount
            FlowDirections = flowDirections
            Id = id
            Livemode = livemode
            OnBehalfOf = onBehalfOf
            PaymentMethod = paymentMethod
            PaymentMethodDetails = paymentMethodDetails
            SetupError = setupError
            SetupIntent = setupIntent
            Status = status
            Usage = usage
            AttachToSelf = attachToSelf
        }

module SetupAttempt =
    ///String representing the object's type. Objects of the same type share the same value.
    let object = "setup_attempt"

