namespace Stripe.SetupAttempt

open System.Text.Json.Serialization
open FunStripe
open System
open Stripe.PaymentMethod

[<System.CodeDom.Compiler.GeneratedCode("FunStripe", "1.0.0")>]
type SetupAttemptCustomer'AnyOf =
    | String of string
    | Customer of Customer
    | DeletedCustomer of DeletedCustomer

[<Struct>]
type SetupAttemptFlowDirections =
    | Inbound
    | Outbound

type SetupAttemptPaymentMethodDetailsAcssDebit =
    { SetupAttemptPaymentMethodDetailsAcssDebit: string option }

type SetupAttemptPaymentMethodDetailsAmazonPay =
    { SetupAttemptPaymentMethodDetailsAmazonPay: string option }

type SetupAttemptPaymentMethodDetailsAuBecsDebit =
    { SetupAttemptPaymentMethodDetailsAuBecsDebit: string option }

type SetupAttemptPaymentMethodDetailsBacsDebit =
    { SetupAttemptPaymentMethodDetailsBacsDebit: string option }

[<Struct>]
type SetupAttemptPaymentMethodDetailsBancontactPreferredLanguage =
    | De
    | En
    | Fr
    | Nl

type SetupAttemptPaymentMethodDetailsBancontact =
    {
        /// Bank code of bank associated with the bank account.
        BankCode: string option
        /// Name of the bank associated with the bank account.
        BankName: string option
        /// Bank Identifier Code of the bank associated with the bank account.
        Bic: string option
        /// The ID of the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
        GeneratedSepaDebit: StripeId<Markers.PaymentMethod> option
        /// The mandate for the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
        GeneratedSepaDebitMandate: StripeId<Markers.Mandate> option
        /// Last four characters of the IBAN.
        [<JsonPropertyName("iban_last4")>]
        IbanLast4: string option
        /// Preferred language of the Bancontact authorization page that the customer is redirected to.
        /// Can be one of `en`, `de`, `fr`, or `nl`
        PreferredLanguage: SetupAttemptPaymentMethodDetailsBancontactPreferredLanguage option
        /// Owner's verified full name. Values are verified or provided by Bancontact directly
        /// (if supported) at the time of authorization or settlement. They cannot be set or mutated.
        VerifiedName: string option
    }

type SetupAttemptPaymentMethodDetailsBoleto =
    { SetupAttemptPaymentMethodDetailsBoleto: string option }

type SetupAttemptPaymentMethodDetailsCardBrand =
    | Amex
    | CartesBancaires
    | Diners
    | Discover
    | EftposAu
    | Jcb
    | Link
    | Mastercard
    | Unionpay
    | Visa
    | Unknown

[<Struct>]
type SetupAttemptPaymentMethodDetailsCardChecksAddressLine1Check =
    | Pass
    | Fail
    | Unavailable
    | Unchecked

[<Struct>]
type SetupAttemptPaymentMethodDetailsCardChecksAddressPostalCodeCheck =
    | Pass
    | Fail
    | Unavailable
    | Unchecked

[<Struct>]
type SetupAttemptPaymentMethodDetailsCardChecksCvcCheck =
    | Pass
    | Fail
    | Unavailable
    | Unchecked

type SetupAttemptPaymentMethodDetailsCardChecks =
    {
        /// If a address line1 was provided, results of the check, one of `pass`, `fail`, `unavailable`, or `unchecked`.
        [<JsonPropertyName("address_line1_check")>]
        AddressLine1Check: SetupAttemptPaymentMethodDetailsCardChecksAddressLine1Check option
        /// If a address postal code was provided, results of the check, one of `pass`, `fail`, `unavailable`, or `unchecked`.
        AddressPostalCodeCheck: SetupAttemptPaymentMethodDetailsCardChecksAddressPostalCodeCheck option
        /// If a CVC was provided, results of the check, one of `pass`, `fail`, `unavailable`, or `unchecked`.
        CvcCheck: SetupAttemptPaymentMethodDetailsCardChecksCvcCheck option
    }

[<Struct>]
type SetupAttemptPaymentMethodDetailsCardFunding =
    | Credit
    | Debit
    | Prepaid
    | Unknown

type SetupAttemptPaymentMethodDetailsCardNetwork =
    | Amex
    | CartesBancaires
    | Diners
    | Discover
    | EftposAu
    | Interac
    | Jcb
    | Link
    | Mastercard
    | Unionpay
    | Visa
    | Unknown

[<Struct>]
type SetupAttemptPaymentMethodDetailsCardWalletType =
    | ApplePay
    | GooglePay
    | Link

type SetupAttemptPaymentMethodDetailsCardWallet =
    {
        ApplePay: PaymentMethodDetailsCardWalletApplePay option
        GooglePay: PaymentMethodDetailsCardWalletGooglePay option
        /// The type of the card wallet, one of `apple_pay`, `google_pay`, or `link`. An additional hash is included on the Wallet subhash with a name matching this value. It contains additional information specific to the card wallet type.
        Type: SetupAttemptPaymentMethodDetailsCardWalletType
    }

[<Struct>]
type ThreeDSecureDetailsAuthenticationFlow =
    | Challenge
    | Frictionless

[<Struct>]
type ThreeDSecureDetailsElectronicCommerceIndicator =
    | [<JsonPropertyName("01")>] Numeric01
    | [<JsonPropertyName("02")>] Numeric02
    | [<JsonPropertyName("05")>] Numeric05
    | [<JsonPropertyName("06")>] Numeric06
    | [<JsonPropertyName("07")>] Numeric07

type ThreeDSecureDetailsResult =
    | AttemptAcknowledged
    | Authenticated
    | Exempted
    | Failed
    | NotSupported
    | ProcessingError

type ThreeDSecureDetailsResultReason =
    | Abandoned
    | Bypassed
    | Canceled
    | CardNotEnrolled
    | NetworkNotSupported
    | ProtocolError
    | Rejected

[<Struct>]
type ThreeDSecureDetailsVersion =
    | [<JsonPropertyName("1.0.2")>] Numeric102
    | [<JsonPropertyName("2.1.0")>] Numeric210
    | [<JsonPropertyName("2.2.0")>] Numeric220
    | [<JsonPropertyName("2.3.0")>] Numeric230
    | [<JsonPropertyName("2.3.1")>] Numeric231

type ThreeDSecureDetails =
    {
        /// For authenticated transactions: how the customer was authenticated by
        /// the issuing bank.
        AuthenticationFlow: ThreeDSecureDetailsAuthenticationFlow option
        /// The Electronic Commerce Indicator (ECI). A protocol-level field
        /// indicating what degree of authentication was performed.
        ElectronicCommerceIndicator: ThreeDSecureDetailsElectronicCommerceIndicator option
        /// Indicates the outcome of 3D Secure authentication.
        Result: ThreeDSecureDetailsResult option
        /// Additional information about why 3D Secure succeeded or failed based
        /// on the `result`.
        ResultReason: ThreeDSecureDetailsResultReason option
        /// The 3D Secure 1 XID or 3D Secure 2 Directory Server Transaction ID
        /// (dsTransId) for this payment.
        TransactionId: string option
        /// The version of 3D Secure that was used.
        Version: ThreeDSecureDetailsVersion option
    }

type SetupAttemptPaymentMethodDetailsCard =
    {
        /// Card brand. Can be `amex`, `cartes_bancaires`, `diners`, `discover`, `eftpos_au`, `jcb`, `link`, `mastercard`, `unionpay`, `visa` or `unknown`.
        Brand: SetupAttemptPaymentMethodDetailsCardBrand option
        /// Check results by Card networks on Card address and CVC at the time of authorization
        Checks: SetupAttemptPaymentMethodDetailsCardChecks option
        /// Two-letter ISO code representing the country of the card. You could use this attribute to get a sense of the international breakdown of cards you've collected.
        Country: IsoTypes.IsoCountryCode option
        /// A high-level description of the type of cards issued in this range. (For internal use only and not typically available in standard API requests.)
        Description: string option
        /// Two-digit number representing the card's expiration month.
        ExpMonth: int option
        /// Four-digit number representing the card's expiration year.
        ExpYear: int option
        /// Uniquely identifies this particular card number. You can use this attribute to check whether two customers who’ve signed up with you are using the same card number, for example. For payment methods that tokenize card information (Apple Pay, Google Pay), the tokenized number might be provided instead of the underlying card number.
        /// *As of May 1, 2021, card fingerprint in India for Connect changed to allow two fingerprints for the same card---one for India and one for the rest of the world.*
        Fingerprint: string option
        /// Card funding type. Can be `credit`, `debit`, `prepaid`, or `unknown`.
        Funding: SetupAttemptPaymentMethodDetailsCardFunding option
        /// Issuer identification number of the card. (For internal use only and not typically available in standard API requests.)
        Iin: string option
        /// The name of the card's issuing bank. (For internal use only and not typically available in standard API requests.)
        Issuer: string option
        /// The last four digits of the card.
        [<JsonPropertyName("last4")>]
        Last4: string option
        /// True if this payment was marked as MOTO and out of scope for SCA.
        Moto: bool option
        /// Identifies which network this charge was processed on. Can be `amex`, `cartes_bancaires`, `diners`, `discover`, `eftpos_au`, `interac`, `jcb`, `link`, `mastercard`, `unionpay`, `visa`, or `unknown`.
        Network: SetupAttemptPaymentMethodDetailsCardNetwork option
        /// Populated if this authorization used 3D Secure authentication.
        ThreeDSecure: ThreeDSecureDetails option
        /// If this Card is part of a card wallet, this contains the details of the card wallet.
        Wallet: SetupAttemptPaymentMethodDetailsCardWallet option
    }

type SetupAttemptPaymentMethodDetailsCardPresent =
    {
        /// The ID of the Card PaymentMethod which was generated by this SetupAttempt.
        GeneratedCard: StripeId<Markers.PaymentMethod> option
        /// Details about payments collected offline.
        Offline: PaymentMethodDetailsCardPresentOffline option
    }

type SetupAttemptPaymentMethodDetailsCashapp =
    { SetupAttemptPaymentMethodDetailsCashapp: string option }

type SetupAttemptPaymentMethodDetailsIdealBank =
    | AbnAmro
    | Adyen
    | AsnBank
    | Bunq
    | Buut
    | Finom
    | Handelsbanken
    | Ing
    | Knab
    | Mollie
    | Moneyou
    | N26
    | Nn
    | Rabobank
    | Regiobank
    | Revolut
    | SnsBank
    | TriodosBank
    | VanLanschot
    | Yoursafe

type SetupAttemptPaymentMethodDetailsIdealBic =
    | [<JsonPropertyName("ABNANL2A")>] ABNANL2A
    | [<JsonPropertyName("ADYBNL2A")>] ADYBNL2A
    | [<JsonPropertyName("ASNBNL21")>] ASNBNL21
    | [<JsonPropertyName("BITSNL2A")>] BITSNL2A
    | [<JsonPropertyName("BUNQNL2A")>] BUNQNL2A
    | [<JsonPropertyName("BUUTNL2A")>] BUUTNL2A
    | [<JsonPropertyName("FNOMNL22")>] FNOMNL22
    | [<JsonPropertyName("FVLBNL22")>] FVLBNL22
    | [<JsonPropertyName("HANDNL2A")>] HANDNL2A
    | [<JsonPropertyName("INGBNL2A")>] INGBNL2A
    | [<JsonPropertyName("KNABNL2H")>] KNABNL2H
    | [<JsonPropertyName("MLLENL2A")>] MLLENL2A
    | [<JsonPropertyName("MOYONL21")>] MOYONL21
    | [<JsonPropertyName("NNBANL2G")>] NNBANL2G
    | [<JsonPropertyName("NTSBDEB1")>] NTSBDEB1
    | [<JsonPropertyName("RABONL2U")>] RABONL2U
    | [<JsonPropertyName("RBRBNL21")>] RBRBNL21
    | [<JsonPropertyName("REVOIE23")>] REVOIE23
    | [<JsonPropertyName("REVOLT21")>] REVOLT21
    | [<JsonPropertyName("SNSBNL2A")>] SNSBNL2A
    | [<JsonPropertyName("TRIONL2U")>] TRIONL2U

type SetupAttemptPaymentMethodDetailsIdeal =
    {
        /// The customer's bank. Can be one of `abn_amro`, `adyen`, `asn_bank`, `bunq`, `buut`, `finom`, `handelsbanken`, `ing`, `knab`, `mollie`, `moneyou`, `n26`, `nn`, `rabobank`, `regiobank`, `revolut`, `sns_bank`, `triodos_bank`, `van_lanschot`, or `yoursafe`.
        Bank: SetupAttemptPaymentMethodDetailsIdealBank option
        /// The Bank Identifier Code of the customer's bank.
        Bic: SetupAttemptPaymentMethodDetailsIdealBic option
        /// The ID of the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
        GeneratedSepaDebit: StripeId<Markers.PaymentMethod> option
        /// The mandate for the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
        GeneratedSepaDebitMandate: StripeId<Markers.Mandate> option
        /// Last four characters of the IBAN.
        [<JsonPropertyName("iban_last4")>]
        IbanLast4: string option
        /// Owner's verified full name. Values are verified or provided by iDEAL directly
        /// (if supported) at the time of authorization or settlement. They cannot be set or mutated.
        VerifiedName: string option
    }

type SetupAttemptPaymentMethodDetailsKakaoPay =
    { SetupAttemptPaymentMethodDetailsKakaoPay: string option }

type SetupAttemptPaymentMethodDetailsKlarna =
    { SetupAttemptPaymentMethodDetailsKlarna: string option }

type SetupAttemptPaymentMethodDetailsKrCard =
    { SetupAttemptPaymentMethodDetailsKrCard: string option }

type SetupAttemptPaymentMethodDetailsLink =
    { SetupAttemptPaymentMethodDetailsLink: string option }

type SetupAttemptPaymentMethodDetailsNaverPay =
    {
        /// Uniquely identifies this particular Naver Pay account. You can use this attribute to check whether two Naver Pay accounts are the same.
        BuyerId: string option
    }

type SetupAttemptPaymentMethodDetailsNzBankAccount =
    { SetupAttemptPaymentMethodDetailsNzBankAccount: string option }

type SetupAttemptPaymentMethodDetailsPaypal =
    { SetupAttemptPaymentMethodDetailsPaypal: string option }

type SetupAttemptPaymentMethodDetailsPayto =
    { SetupAttemptPaymentMethodDetailsPayto: string option }

type SetupAttemptPaymentMethodDetailsPix =
    { SetupAttemptPaymentMethodDetailsPix: string option }

type SetupAttemptPaymentMethodDetailsRevolutPay =
    { SetupAttemptPaymentMethodDetailsRevolutPay: string option }

type SetupAttemptPaymentMethodDetailsSepaDebit =
    { SetupAttemptPaymentMethodDetailsSepaDebit: string option }

[<Struct>]
type SetupAttemptPaymentMethodDetailsSofortPreferredLanguage =
    | De
    | En
    | Fr
    | Nl

type SetupAttemptPaymentMethodDetailsSofort =
    {
        /// Bank code of bank associated with the bank account.
        BankCode: string option
        /// Name of the bank associated with the bank account.
        BankName: string option
        /// Bank Identifier Code of the bank associated with the bank account.
        Bic: string option
        /// The ID of the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
        GeneratedSepaDebit: StripeId<Markers.PaymentMethod> option
        /// The mandate for the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
        GeneratedSepaDebitMandate: StripeId<Markers.Mandate> option
        /// Last four characters of the IBAN.
        [<JsonPropertyName("iban_last4")>]
        IbanLast4: string option
        /// Preferred language of the Sofort authorization page that the customer is redirected to.
        /// Can be one of `en`, `de`, `fr`, or `nl`
        PreferredLanguage: SetupAttemptPaymentMethodDetailsSofortPreferredLanguage option
        /// Owner's verified full name. Values are verified or provided by Sofort directly
        /// (if supported) at the time of authorization or settlement. They cannot be set or mutated.
        VerifiedName: string option
    }

type SetupAttemptPaymentMethodDetailsUpi =
    { SetupAttemptPaymentMethodDetailsUpi: string option }

type SetupAttemptPaymentMethodDetailsUsBankAccount =
    { SetupAttemptPaymentMethodDetailsUsBankAccount: string option }

type SetupAttemptPaymentMethodDetails =
    {
        AcssDebit: SetupAttemptPaymentMethodDetailsAcssDebit option
        AmazonPay: SetupAttemptPaymentMethodDetailsAmazonPay option
        AuBecsDebit: SetupAttemptPaymentMethodDetailsAuBecsDebit option
        BacsDebit: SetupAttemptPaymentMethodDetailsBacsDebit option
        Bancontact: SetupAttemptPaymentMethodDetailsBancontact option
        Boleto: SetupAttemptPaymentMethodDetailsBoleto option
        Card: SetupAttemptPaymentMethodDetailsCard option
        CardPresent: SetupAttemptPaymentMethodDetailsCardPresent option
        Cashapp: SetupAttemptPaymentMethodDetailsCashapp option
        Ideal: SetupAttemptPaymentMethodDetailsIdeal option
        KakaoPay: SetupAttemptPaymentMethodDetailsKakaoPay option
        Klarna: SetupAttemptPaymentMethodDetailsKlarna option
        KrCard: SetupAttemptPaymentMethodDetailsKrCard option
        Link: SetupAttemptPaymentMethodDetailsLink option
        NaverPay: SetupAttemptPaymentMethodDetailsNaverPay option
        NzBankAccount: SetupAttemptPaymentMethodDetailsNzBankAccount option
        Paypal: SetupAttemptPaymentMethodDetailsPaypal option
        Payto: SetupAttemptPaymentMethodDetailsPayto option
        Pix: SetupAttemptPaymentMethodDetailsPix option
        RevolutPay: SetupAttemptPaymentMethodDetailsRevolutPay option
        SepaDebit: SetupAttemptPaymentMethodDetailsSepaDebit option
        Sofort: SetupAttemptPaymentMethodDetailsSofort option
        /// The type of the payment method used in the SetupIntent (e.g., `card`). An additional hash is included on `payment_method_details` with a name matching this value. It contains confirmation-specific information for the payment method.
        Type: string
        Upi: SetupAttemptPaymentMethodDetailsUpi option
        UsBankAccount: SetupAttemptPaymentMethodDetailsUsBankAccount option
    }

type SetupAttemptStatus =
    | RequiresConfirmation
    | RequiresAction
    | Processing
    | Succeeded
    | Failed
    | Abandoned

[<Struct>]
type SetupAttemptUsage =
    | OffSession
    | OnSession

/// A SetupAttempt describes one attempted confirmation of a SetupIntent,
/// whether that confirmation is successful or unsuccessful. You can use
/// SetupAttempts to inspect details of a specific attempt at setting up a
/// payment method using a SetupIntent.
type SetupAttempt =
    {
        /// The value of [application](https://docs.stripe.com/api/setup_intents/object#setup_intent_object-application) on the SetupIntent at the time of this confirmation.
        Application: StripeId<Markers.Application> option
        /// If present, the SetupIntent's payment method will be attached to the in-context Stripe Account.
        /// It can only be used for this Stripe Account’s own money movement flows like InboundTransfer and OutboundTransfers. It cannot be set to true when setting up a PaymentMethod for a Customer, and defaults to false when attaching a PaymentMethod to a Customer.
        AttachToSelf: bool option
        /// Time at which the object was created. Measured in seconds since the Unix epoch.
        Created: DateTime
        /// The value of [customer](https://docs.stripe.com/api/setup_intents/object#setup_intent_object-customer) on the SetupIntent at the time of this confirmation.
        Customer: SetupAttemptCustomer'AnyOf option
        /// The value of [customer_account](https://docs.stripe.com/api/setup_intents/object#setup_intent_object-customer_account) on the SetupIntent at the time of this confirmation.
        CustomerAccount: string option
        /// Indicates the directions of money movement for which this payment method is intended to be used.
        /// Include `inbound` if you intend to use the payment method as the origin to pull funds from. Include `outbound` if you intend to use the payment method as the destination to send funds to. You can include both if you intend to use the payment method for both purposes.
        FlowDirections: SetupAttemptFlowDirections list option
        /// Unique identifier for the object.
        Id: string
        /// If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
        Livemode: bool
        /// The value of [on_behalf_of](https://docs.stripe.com/api/setup_intents/object#setup_intent_object-on_behalf_of) on the SetupIntent at the time of this confirmation.
        OnBehalfOf: StripeId<Markers.Account> option
        /// ID of the payment method used with this SetupAttempt.
        PaymentMethod: StripeId<Markers.PaymentMethod>
        PaymentMethodDetails: SetupAttemptPaymentMethodDetails
        /// The error encountered during this attempt to confirm the SetupIntent, if any.
        SetupError: ApiErrors option
        /// ID of the SetupIntent that this attempt belongs to.
        SetupIntent: StripeId<Markers.SetupIntent>
        /// Status of this SetupAttempt, one of `requires_confirmation`, `requires_action`, `processing`, `succeeded`, `failed`, or `abandoned`.
        Status: SetupAttemptStatus
        /// The value of [usage](https://docs.stripe.com/api/setup_intents/object#setup_intent_object-usage) on the SetupIntent at the time of this confirmation, one of `off_session` or `on_session`.
        Usage: SetupAttemptUsage
    }

module SetupAttempt =
    ///String representing the object's type. Objects of the same type share the same value.
    let object = "setup_attempt"

